import * as React from 'react';
import { Link as LinkIcon, Loader2 } from 'lucide-react';
import { api } from '../../../lib/api';

type Props={onAuthenticated:(token:string)=>void};
export function AuthScreen({onAuthenticated}:Props){
 const[mode,setMode]=React.useState<'login'|'register'>('login');
 const[email,setEmail]=React.useState('');const[password,setPassword]=React.useState('');const[confirm,setConfirm]=React.useState('');
 const[loading,setLoading]=React.useState(false);const[message,setMessage]=React.useState<string|null>(null);const[error,setError]=React.useState<string|null>(null);
 async function submit(e:React.FormEvent){e.preventDefault();setError(null);setMessage(null);if(password.length<8){setError('Password must be at least 8 characters.');return}if(mode==='register'&&password!==confirm){setError('Passwords do not match.');return}setLoading(true);try{if(mode==='register'){await api.register(email,password);setMode('login');setMessage('Account created. Please sign in.');return}const res=await api.login(email,password);localStorage.setItem('linkstream_token',res.token);onAuthenticated(res.token)}catch(err){setError(err instanceof Error?err.message:'Authentication failed.')}finally{setLoading(false)}}
 return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:24,background:'#f8fafc'}}><section className="card" style={{width:'100%',maxWidth:440,padding:32}}><div style={{display:'flex',alignItems:'center',gap:12,justifyContent:'center',marginBottom:28}}><span style={{background:'#4f46e5',color:'#fff',borderRadius:12,padding:10}}><LinkIcon size={22}/></span><h1 style={{margin:0}}>Link<span className="primary">Stream</span></h1></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,background:'#f1f5f9',borderRadius:12,padding:6,marginBottom:24}}><button className={`btn ${mode==='login'?'':'secondary'}`} type="button" onClick={()=>setMode('login')}>Sign In</button><button className={`btn ${mode==='register'?'':'secondary'}`} type="button" onClick={()=>setMode('register')}>Create</button></div>{error&&<div className="notice">{error}</div>}{message&&<div style={{border:'1px solid #bbf7d0',background:'#f0fdf4',color:'#166534',borderRadius:10,padding:12,marginBottom:16,fontSize:14}}>{message}</div>}<form onSubmit={submit} style={{display:'grid',gap:14}}><label>Email<input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="demo@email.com"/></label><label>Password<input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="••••••••"/></label>{mode==='register'&&<label>Confirm password<input className="input" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required placeholder="••••••••"/></label>}<button className="btn" disabled={loading}>{loading?<Loader2 className="animate-spin" size={18}/>:mode==='login'?'Sign In':'Create Account'}</button></form><p className="muted" style={{fontSize:12,textAlign:'center',marginTop:24}}>API Gateway: http://localhost:8080</p></section></main>}
