direction: left

S: Services {
    US: URL Service
    AS: Analytics Service
    NS: Notification Service
    URS: User Service
}

D: Databases {
    UDB: urldb (5432)
    ADB: analyticsdb (5433)
    UUDB: usersdb (5434)
    NDB: notificationdb (5435)
}

US -> UDB
AS -> ADB
NS -> NDB
URS -> UUDB
